# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160804_1454'),
        ('articles', '0002_article_public'),
    ]

    operations = [
    ]
